# POST http://localhost:4000/users/register
# Content-Type: application/json

# {
#     "email": "A@gmail.com", "password": "123456", "fullname": "A"
# }

# POST http://localhost:4000/users/login
# Content-Type: application/json

# {
#     "email": "A@gmail.com", "password": "123456"
# }

POST http://localhost:4000/users/login/facebook
Content-Type: application/json

{
    "accessToken": "EAAFjrGiZBHKwBADqcpt7b2TH1f1fhteZA4N9sfDRtBjl2eRzJs4SgguHY4NC0ZCxqR0OUvTlDlXu07ZCPItx2P5bTkf2fw5HG6xEcqCgyXrLabY78AiFhm1nTd8wLLANZAdbv1XANKTHr7xePagt7z9PzEsXYXfZB4rzsHZBYZAe05xSTmlbhnXdo30UEajEUDySXDLJVw5ZAZCNFL76bfZAujIL5cjgHoC7dyJMsAhK6g5IYvMaB6upmVM",
    "userId": "741376040181595"
}